language: java

jdk:
  - oraclejdk8

script:
  ./gradlew check && ./gradlew -p sample check

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

notifications:
  email: true

